### ISSUE TITLE
PHP notices.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/similar#10]
While testing https://github.com/backdrop/backdrop-issues/issues/2820, I noticed the following errors when viewing pages that have the similar content block:

```
Notice: Undefined variable: body in similar_handler_argument_nid->query() (line 362 of /modules/similar/views/similar_handler_argument_nid.inc).
```

```
Notice: Undefined index: safe_value in similar_handler_argument_nid->query() (line 347 of /modules/similar/views/similar_handler_argument_nid.inc).
```

**Comment by jenlampton** [comment]
I'm unable to reproduce these PHP notices. Which version of PHP are you using?

**Comment by jenlampton** [comment]
I have a site now where I can see these. Will try to clean them up!

**Comment by jenlampton** [comment]
Pushed 2 commits to fix these.
